TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "DEVICE_ID"
SILO = "NO"
REALM = "NO"
DATE = "NO"

SQL_REQ = '''
SELECT DISTINCT
    MIN(CLIENT_TIME) AS "CREATED",
    MAX(CLIENT_TIME) AS "LAST_SEEN",
    DATA_CENTER_ID AS "SILO",
    USER_ID AS "DEVICE",
    FED_ID AS "FED",
    MAX(PROGRESS_INDEX01) AS "LEVEL",
    INGAME_NICKNAME_ACTIVE AS "NAME",
    COUNT(DISTINCT FED_ID) OVER (PARTITION BY DEVICE) AS "TOTAL_ACCOUNTS_USED"
FROM
    "ELEPHANT_DB"."AOV"."PLAYER_CONNECTION_REPORT"
WHERE
    DEVICE = '{filter_value}'
GROUP BY
    SILO,
    DEVICE,
    FED,
    NAME
ORDER BY
    LAST_SEEN DESC
LIMIT 10000
;
'''