TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "YES"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''
SELECT
    CLIENT_TIME AS "TIME",
    EFFECT_NAME AS "EFFECT",
    EFFECT_INT AS "EFFECT_INT",
    EFFECT_SOURCE AS "SOURCE",
    EFFECT_DATA AS "DATA",
    EFFECT_DURATION AS "DURATION",
    DATA_CENTER_ID AS "SILO",
    FED_ID AS "FED",
    REALM_ID_CURRENT AS "C_REALM",
    REALM_ID AS "REALM",
    PLATFORM AS "PLATFORM",
    USER_ID AS "DEVICE"
FROM
    "ELEPHANT_DB"."MOE"."EFFECT_CHANGE"
WHERE
    CLIENT_TIME > '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND DATA_CENTER_ID LIKE '{silo}'
    AND FED_ID = '{account}'
    
ORDER BY TIME ASC
;
'''