TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "TRANSACTION_ID"
SILO = "NO"
REALM = "NO"
DATE = "NO"

SQL_REQ = '''
SELECT DISTINCT
    T_EVENT.EVENT_NAME,
    T_IAP.*
FROM "ELEPHANT_DB"."MOE"."IAP" AS T_IAP
    INNER JOIN "ELEPHANT_DB"."DIMENSIONS"."EVENT" AS T_EVENT
    ON (T_IAP.EVENT_ID = T_EVENT.EVENT_ID)
WHERE
    T_IAP.FED_ID = '{account}'
    AND T_IAP.TRANSACTION_ID::INT LIKE '%{filter_value}%'
LIMIT 1000
;
'''