TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "NO"
SILO = "YES"
REALM = "NO"
DATE = "YES"

SQL_REQ = '''

SELECT DISTINCT
    DATE(CLIENT_TIME) AS "DATE",
    CLIENT_TIME AS "TIME",
    DATA_CENTER_ID AS "SILO",
    VERSION AS "GAME_VERSION",
    PLATFORM AS "PLATFORM",
    COUNTRY AS "COUNTRY",
    COUNTRY_CODE AS "COUNTRY_CODE",
    FED_ID AS "FED",
    PROGRESS_INDEX02 AS "CASTLE_LEVEL",
    TRANSACTION_ID AS "TRANSACTION",
    ORIGINAL_CONTENT_ID AS "PACK_NAME",
    TO_NUMBER(PRICE_PAID,20,2) AS "PRICE",
    CURRENCY AS "CURRENCY",
    USER_ID AS "DEVICE",
    ANON_ID AS "ANON",
    COUNT(TRANSACTION) OVER(PARTITION BY FED) AS "TOTAL_TR_PER_FED",
    COUNT(TRANSACTION) OVER() AS "TOTAL_TR_OVERALL",
    TO_NUMBER((TOTAL_TR_PER_FED / TOTAL_TR_OVERALL * 100),38,2) AS "%_OVER_PERIOD"
FROM
    "ELEPHANT_DB"."MOE"."IAP"
WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND IAP_ACTION = 'New Purchase'
    AND SILO LIKE '{silo}'
ORDER BY TIME
LIMIT 10000
;

'''