TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "YES"
REALM = "NO"
DATE = "YES"

SQL_REQ = '''
SELECT DISTINCT
    PLAYER_LOST_UNITS:l::STRING AS "LOST",
    PLAYER_LOST_UNITS:w::STRING AS "WOUNDED",
    RESOURCES_STOLEN AS "RESOURCES",
    COUNT(DISTINCT COMBAT_ID) AS "TOTAL_BATTLES"

FROM "ELEPHANT_DB"."MOE"."COMBAT_INTERACTION"
WHERE 
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND FED_ID = '{account}'
    AND COMBAT_INT LIKE 'Defend%'
GROUP BY LOST, WOUNDED, RESOURCES
LIMIT 5000
;
'''