TYPE = "Player"
CREDENTIAL = "YES"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''
SELECT
    DATE(T_SCORE.CLIENT_TIME) AS "DATE",
    T_SCORE.CLIENT_TIME AS "TIME",
    T_SCORE.DATA_CENTER_ID AS "SILO",
    T_SCORE.EVENT_DATA:realm_id_current::INT AS "REALM",
    T_SCORE.EVENT_DATA:all_id::INT AS "ALLIANCE_ID",
    T_SCORE.EVENT_DATA:progress_index02::INT AS "CHAMP_LEVEL",
    T_SCORE.FED_ID AS "FED",
    T_Element_5.NAME AS "SCORE_TYPE",
    T_Element_2.NAME AS "ACTION",
    T_SCORE.EVENT_DATA:score_earned::INT AS "SCORE_EARNED",
    T_SCORE.EVENT_DATA:score_lost::INT AS "SCORE_LOST",
    T_SCORE.EVENT_DATA:score_leftover::INT AS "SCORE_LEFTOVER",
    T_SCORE.EVENT_DATA:score_balance::INT AS "SCORE_BALANCE",
    T_SCORE.EVENT_DATA:score_progress_level::INT AS "PROGRESS_LEVEL",
    T_SCORE.EVENT_DATA:score_data::STRING AS "SCORE_DATA",
    T_SCORE.EVENT_DATA:event_bracket::INT AS "BRACKET",
    T_Element.NAME AS "TLE_TYPE",
    T_SCORE.EVENT_DATA:event_name::STRING AS "TLE_NAME",
    T_SCORE.EVENT_DATA:event_type::STRING AS "EVENT_DETAILS",
    T_Element_3.NAME AS "SCORE_OBJECTIVE",
    T_Element_4.NAME AS "SCORE_TRESHHOLD",
    T_SCORE.EVENT_DATA:item_name::INT AS "ITEM_ID",
    T_Element_6.NAME AS "ITEM_NAME",
    T_SCORE.EVENT_DATA:target_item::INT AS "T_ITEM_ID",
    T_Element_7.NAME AS "T_ITEM_NAME",
    T_SCORE.EVENT_DATA:target_item2::INT AS "T_ITEM_ID_2",
    T_Element_8.NAME AS "T_ITEM_NAME_2",
    T_SCORE.EVENT_DATA:tle_event_id::STRING AS "TLE_ID",
    T_SCORE.EVENT_DATA:region_id::STRING AS "REGION",
    T_SCORE.EVENT_DATA:coord_id::STRING AS "COORD"
        
FROM "ELEPHANT_DB"."MOE"."SCORE_INTERACTION_RAW" AS T_SCORE

LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element
    ON (T_SCORE.EVENT_DATA:criteria_actor::INT = T_Element.ID)
LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element_2
    ON (T_SCORE.EVENT_DATA:score_int::INT = T_Element_2.ID)
LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element_3
    ON (T_SCORE.EVENT_DATA:score_objective::INT = T_Element_3.ID)
LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element_4
    ON (T_SCORE.EVENT_DATA:score_threshold::INT = T_Element_4.ID)
LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element_5
    ON (T_SCORE.EVENT_DATA:score_type::INT = T_Element_5.ID)
LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element_6
    ON (T_SCORE.EVENT_DATA:item_name::INT = T_Element_6.ID)
LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element_7
    ON (T_SCORE.EVENT_DATA:target_item::INT = T_Element_7.ID)
LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."ELEMENT" AS T_Element_8
    ON (T_SCORE.EVENT_DATA:target_item2::INT = T_Element_8.ID)
WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND FED_ID = '{account}'
ORDER BY CLIENT_TIME ASC
LIMIT 10000
;
'''