TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ = '''

SELECT DISTINCT
    DATE(CLIENT_TIME) AS "DATE",
    DATA_CENTER_ID AS "SILO",
    PLATFORM AS "PLATFORM",
    VERSION AS "GAME_VERSION",
    COUNTRY AS "COUNTRY",
    COUNTRY_CODE AS "COUNTRY_CODE",
    SUM(TO_NUMBER(PRICE_PAID,20,2)) AS "TOTAL_PAID",
    CURRENCY AS "CURRENCY",
    COUNT(DISTINCT FED_ID) AS "TOTAL_ACCOUNTS",
    COUNT(DISTINCT TRANSACTION_ID) AS "TOTAL_TR",
    SUM(TOTAL_TR) OVER() AS "TOTAL_PERIOD_TR",
    TO_NUMBER((TOTAL_TR / TOTAL_PERIOD_TR * 100),38,2) AS "%_OVER_PERIOD"
FROM
    "ELEPHANT_DB"."MOE"."IAP"
WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND IAP_ACTION = 'New Purchase'
    AND SILO LIKE '{silo}'
GROUP BY
    DATE, SILO, PLATFORM,GAME_VERSION,COUNTRY,COUNTRY_CODE,CURRENCY
ORDER BY DATE ASC
LIMIT 10000
;
'''