TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "NO"
SILO = "YES"
REALM = "YES"
DATE = "YES"

SQL_REQ =   '''
SELECT DISTINCT
    DATA_CENTER_ID AS "SILO",
    EVENT_DATA:realm_id::INT AS "REALM",
    EVENT_DATA:game_player_id::INT AS "PLAYER_ID",
    FED_ID AS "FED",
    USER_ID AS "DEVICE",
    MAX(CLIENT_TIME) AS LAST_SEEN,
    COUNT(DISTINCT FED) OVER(PARTITION BY DEVICE) AS "TOTAL_ACCOUNTS",
    MAX(EVENT_DATA:ingame_nickname_active::STRING) AS "NAME",
    MAX(EVENT_DATA:progress_index02::INT) AS "CASTLE_LEVEL",
    MAX(EVENT_DATA:all_id::INT) AS "ALLIANCE_ID",
    MAX(EVENT_DATA:all_name_tag::STRING) AS "ALLIANCE_TAG",
    MAX(EVENT_DATA:all_name::STRING) AS "ALLIANCE_NAME",
    MAX(EVENT_DATA:consumable_power_balance::INT) AS "ARMY_MIGHT",
    MAX(EVENT_DATA:permanent_power_balance::INT) AS "CITY_MIGHT",
    ARMY_MIGHT + CITY_MIGHT AS "TOTAL_MIGHT"
FROM
    "ELEPHANT_DB"."MOE"."PLAYER_CONNECTION_REPORT_RAW"
WHERE 
    CLIENT_TIME >= '{st_date}'
      AND CLIENT_TIME < '{end_date}'
      AND "SILO" LIKE '{silo}'
      AND "REALM" = '{realm}'
      AND "DEVICE" > 0
GROUP BY 1,2,3,4,5
ORDER BY TOTAL_ACCOUNTS DESC, DEVICE ASC, FED ASC, LAST_SEEN DESC
LIMIT 10000
;
'''