TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "NO"
SILO = "YES"
REALM = "NO"
DATE = "YES"

SQL_REQ = '''

SELECT DISTINCT
    DATE(CLIENT_TIME) AS "DATE",
    CLIENT_TIME AS "TIME",
    DATA_CENTER_ID AS "SILO",
    VERSION AS "GAME_VERSION",
    PLATFORM AS "PLATFORM",
    COUNTRY AS "COUNTRY",
    COUNTRY_CODE AS "COUNTRY_CODE",
    FED_ID AS "FED",
    MAX(PROGRESS_INDEX02) AS "CASTLE_LEVEL",
    TRANSACTION_ID AS "TRANSACTION_ID",
    ORIGINAL_CONTENT_ID AS "PACK_NAME",
    SUM(REVENUE_EUR)::INT AS "REVENUE",
    SUM(REVENUE) OVER() AS "TOTAL_REVENUE",
    TO_NUMBER(PRICE_PAID,20,2) AS "PRICE",
    CURRENCY AS "CURRENCY",
    USER_ID AS "DEVICE",
    ANON_ID AS "ANON",
    COUNT(TRANSACTION_ID) OVER(PARTITION BY FED) AS "TOTAL_TR_PER_FED",
    COUNT(TRANSACTION_ID) OVER() AS "TOTAL_TR_OVERALL",
    TO_NUMBER((TOTAL_TR_PER_FED / TOTAL_TR_OVERALL * 100),38,2) AS "%_OVER_PERIOD"
FROM
    "ELEPHANT_DB"."MOE"."IAP"
WHERE
    CLIENT_TIME >= '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND IAP_ACTION = 'New Purchase'
    AND SILO LIKE '{silo}'
GROUP BY DATE, TIME, SILO, GAME_VERSION, PLATFORM, COUNTRY, COUNTRY_CODE, FED, TRANSACTION_ID, ORIGINAL_CONTENT_ID, PRICE, CURRENCY, DEVICE, ANON
ORDER BY TIME
LIMIT 10000
;
'''