TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "NO"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ =   '''
SELECT DISTINCT
    DATE(T_IAP.CLIENT_TIME) AS "DATE",
    T_EVENT.EVENT_NAME as "Event",
    T_IAP.ORIGINAL_CONTENT_ID AS "Pack",
    TO_NUMBER((T_IAP.PRICE_PAID),10,2) AS "Price",
    T_IAP.CURRENCY AS "Currency",
    TO_NUMBER((T_IAP.REVENUE_EUR),10,2) AS "R_EUR",
    T_IAP.DATA_CENTER_ID AS "SILO",
    T_IAP.PLATFORM,
    T_IAP.FED_ID AS "FED",
    COUNT(DISTINCT T_IAP.TRANSACTION_ID) AS "Transactions",
    TO_NUMBER(("Transactions" * "R_EUR"),10,2) AS "Revenue"

FROM "ELEPHANT_DB"."MOE"."IAP" AS T_IAP
    LEFT JOIN "ELEPHANT_DB"."DIMENSIONS"."EVENT" AS T_EVENT
    ON (T_IAP.EVENT_ID = T_EVENT.EVENT_ID)
WHERE
    T_IAP.CLIENT_TIME >= '{st_date}'
    AND T_IAP.CLIENT_TIME < '{end_date}'
GROUP BY 1,2,3,4,5,6,7,8,9

ORDER BY "DATE" ASC,"Transactions" DESC
LIMIT 10000
;
'''