TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "PACK NAME"
SILO = "NO"
REALM = "NO"
DATE = "YES"

SQL_REQ = '''
SELECT
    MIN(DATE(T_IAP.CLIENT_TIME)) AS "FROM",
    MAX(DATE(T_IAP.CLIENT_TIME)) AS "TO",
    T_IAP.PACK_NAME AS "PACK",
    T_IAP.PLATFORM AS "PLATFORM",
    T_Country.NAME AS "COUNTRY",
    COUNT(DISTINCT T_IAP.TRANSACTION_ID) AS "SOLD",
    TO_NUMBER(T_IAP.PRICE_PAID,10,2) AS "PRICE",
    T_IAP.CURRENCY AS "CURRENCY",
    "SOLD" * "PRICE" AS "T_AMOUNT",
    SUM(SOLD) OVER () AS "TOTAL_SOLD"
FROM
    "ELEPHANT_DB"."MOE"."IAP" AS T_IAP
LEFT JOIN
    "ELEPHANT_DB"."DIMENSIONS"."COUNTRY" AS T_Country
    ON (T_IAP.COUNTRY = T_Country.CODE)
WHERE
    CLIENT_TIME > '{st_date}'
    AND CLIENT_TIME < '{end_date}'
    AND PACK_NAME LIKE '%{filter_value}%'
GROUP BY 3,4,5,7,8
ORDER BY "FROM","PACK","PLATFORM","CURRENCY","COUNTRY"
LIMIT 10000
;
'''