TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "DEVICE_ID"
SILO = "NO"
REALM = "NO"
DATE = "NO"

SQL_REQ = '''
SELECT
  MAX(T_DET.LAST_SEEN) AS "LAST_SEEN",
  T_DET.SILO AS "SILO",
  T_DET.LAST_REALM AS "REALM",
  T_DET.FED AS "FED",
  T_DET.LAST_NAME AS "NAME",
  T_DET.LAST_ALL_ID AS "ALL_ID",
  T_DET.LAST_ALL_TAG AS "ALL_TAG",
  T_DET.LAST_ALL_NAME AS "ALL_NAME",
  MAX(T_DET.CASTLE_LEVEL) AS "CASTLE_LEVEL",
  T_DET.DEVICE AS "DEVICE",
  COUNT(FED) OVER() AS "TOTAL_ACCOUNTS"

FROM (SELECT DISTINCT
        MAX(CLIENT_TIME) AS "LAST_SEEN",
        USER_ID AS "DEVICE",
        FED_ID AS "FED",
        DATA_CENTER_ID AS "SILO",
        EVENT_DATA:realm_id_current::INT AS "REALM",
        LAST_VALUE(REALM) OVER (PARTITION BY FED ORDER BY LAST_SEEN ASC) AS "LAST_REALM",
        EVENT_DATA:ingame_nickname_active::STRING AS "NAME",
        LAST_VALUE(NAME) OVER (PARTITION BY FED ORDER BY LAST_SEEN ASC) AS "LAST_NAME",
        EVENT_DATA:all_id::STRING AS "ALL_ID",
        LAST_VALUE(ALL_ID) OVER (PARTITION BY FED ORDER BY LAST_SEEN ASC) AS "LAST_ALL_ID",
        EVENT_DATA:all_name_tag::STRING AS "ALL_TAG",
        LAST_VALUE(ALL_TAG) OVER (PARTITION BY FED ORDER BY LAST_SEEN ASC) AS "LAST_ALL_TAG",
        MAX(EVENT_DATA:all_name::STRING) AS "ALL_NAME",
        LAST_VALUE(ALL_NAME) OVER (PARTITION BY FED ORDER BY LAST_SEEN ASC) AS "LAST_ALL_NAME",
        MAX(EVENT_DATA:progress_index02::INT) AS "CASTLE_LEVEL"
    FROM
        "ELEPHANT_DB"."MOE"."PLAYER_CONNECTION_REPORT_RAW" AS T1
    WHERE
        USER_ID = '{filter_value}'
    GROUP BY 2,3,4,5,7,9,11
    LIMIT 1000) AS T_DET

GROUP BY 2,3,4,5,6,7,8,10
ORDER BY LAST_SEEN DESC
;
'''