TYPE = "Alliance"
CREDENTIAL = "NO"
FILTER = "ALLIANCE TAG"
SILO = "YES"
REALM = "YES"
DATE = "YES"

SQL_REQ = '''
SELECT
  T_Pl_Con.DATA_CENTER_ID AS SILO,
  T_Pl_Con.EVENT_DATA:realm_id::INT AS REALM,
  T_Pl_Con.EVENT_DATA:all_id::INT AS ALLIANCE_ID,
  T_Pl_Con.EVENT_DATA:all_name_tag::STRING AS ALLIANCE_TAG,
  T_Pl_Con.EVENT_DATA:all_name::STRING AS ALLIANCE_NAME,
  T_Pl_Con.EVENT_DATA:ingame_nickname_active::STRING AS NAME,
  T_Pl_Con.FED_ID AS FED,
  MAX (DATE(CLIENT_TIME)) AS LAST_SEEN,
  USER_ID AS DEVICE_ID
FROM "ELEPHANT_DB"."MOE"."PLAYER_CONNECTION_REPORT_RAW" AS T_Pl_Con
WHERE 
  CLIENT_TIME > '{st_date}'
  AND CLIENT_TIME < '{end_date}'
  AND DATA_CENTER_ID LIKE '{silo}'
  AND DEVICE_ID > 0
  AND EVENT_DATA:realm_id::INT = {realm}
  AND EVENT_DATA:all_name_tag::STRING LIKE '{filter_value}'
GROUP BY 1,2,3,4,5,6,7,9
ORDER BY (LAST_SEEN) DESC
LIMIT 1000
;
'''